schema = {
    "listen_events" : [
        {"name": "artist", "type": "STRING", "mode": "NULLABLE"},
        {"name": "song", "type": "STRING", "mode": "NULLABLE"},
        {"name": "duration", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "ts", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "sessionId", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "auth", "type": "STRING", "mode": "NULLABLE"},
        {"name": "level", "type": "STRING", "mode": "NULLABLE"},
        {"name": "itemInSession", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "city", "type": "STRING", "mode": "NULLABLE"},
        {"name": "zip", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "state", "type": "STRING", "mode": "NULLABLE"},
        {"name": "userAgent", "type": "STRING", "mode": "NULLABLE"},
        {"name": "lon", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "lat", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "userId", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "lastName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "firstName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "gender", "type": "STRING", "mode": "NULLABLE"},
        {"name": "registration", "type": "INTEGER", "mode": "NULLABLE"}
    ],
    "page_view_events" : [
        {"name": "ts", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "sessionId", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "page", "type": "STRING", "mode": "NULLABLE"},
        {"name": "auth", "type": "STRING", "mode": "NULLABLE"},
        {"name": "method", "type": "STRING", "mode": "NULLABLE"},
        {"name": "status", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "level", "type": "STRING", "mode": "NULLABLE"},
        {"name": "itemInSession", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "city", "type": "STRING", "mode": "NULLABLE"},
        {"name": "zip", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "state", "type": "STRING", "mode": "NULLABLE"},
        {"name": "userAgent", "type": "STRING", "mode": "NULLABLE"},
        {"name": "lon", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "lat", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "userId", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "lastName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "firstName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "gender", "type": "STRING", "mode": "NULLABLE"},
        {"name": "registration", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "artist", "type": "STRING", "mode": "NULLABLE"},
        {"name": "song", "type": "STRING", "mode": "NULLABLE"},
        {"name": "duration", "type": "FLOAT64", "mode": "NULLABLE"}
    ],
    "auth_events" : [
        {"name": "ts", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "sessionId", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "level", "type": "STRING", "mode": "NULLABLE"},
        {"name": "itemInSession", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "city", "type": "STRING", "mode": "NULLABLE"},
        {"name": "zip", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "state", "type": "STRING", "mode": "NULLABLE"},
        {"name": "userAgent", "type": "STRING", "mode": "NULLABLE"},
        {"name": "lon", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "lat", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "userId", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "lastName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "firstName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "gender", "type": "STRING", "mode": "NULLABLE"},
        {"name": "registration", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "success", "type": "BOOLEAN", "mode": "NULLABLE"}
    ],
    "status_change_events": [
        {"name": "ts", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "sessionId", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "auth", "type": "STRING", "mode": "NULLABLE"},
        {"name": "level", "type": "STRING", "mode": "NULLABLE"},
        {"name": "itemInSession", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "city", "type": "STRING", "mode": "NULLABLE"},
        {"name": "zip", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "state", "type": "STRING", "mode": "NULLABLE"},
        {"name": "userAgent", "type": "STRING", "mode": "NULLABLE"},
        {"name": "lon", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "lat", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "userId", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "lastName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "firstName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "gender", "type": "STRING", "mode": "NULLABLE"},
        {"name": "registration", "type": "INTEGER", "mode": "NULLABLE"}
    ],
    "session_start_end_events": [
        {"name": "ts", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "sessionId", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "auth", "type": "STRING", "mode": "NULLABLE"},
        {"name": "level", "type": "STRING", "mode": "NULLABLE"},
        {"name": "itemInSession", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "city", "type": "STRING", "mode": "NULLABLE"},
        {"name": "zip", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "state", "type": "STRING", "mode": "NULLABLE"},
        {"name": "userAgent", "type": "STRING", "mode": "NULLABLE"},
        {"name": "lon", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "lat", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "userId", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "lastName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "firstName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "gender", "type": "STRING", "mode": "NULLABLE"},
        {"name": "registration", "type": "INTEGER", "mode": "NULLABLE"}
    ]

    ,
    "user_info": [
        {"name": "userId", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "lastName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "firstName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "gender", "type": "STRING", "mode": "NULLABLE"},
        {"name": "registration", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "ts", "type": "INTEGER", "mode": "NULLABLE"}
    ]

}
