version: 2

models:
  - name: d_user_profile
    columns:
      - name: user_id
        tests: [not_null, unique]
      - name: tf_updated_at
        tests: [not_null]

  - name: smy_user_behavior_daily__mnp
    columns:
      - name: user_id
        tests: [not_null]
      - name: activity_date
        tests: [not_null]

  - name: smy_user_listening_stats__mnp
    columns:
      - name: user_id
        tests: [not_null]
      - name: activity_date
        tests: [not_null]

  - name: smy_user_subscription_journey__mnp
    columns:
      - name: user_id
        tests: [not_null]

  - name: smy_daily_trending_songs__mnp
    columns:
      - name: activity_date
        tests: [not_null]
      - name: song
        tests: [not_null]

  - name: smy_session_quality_analysis__mnp
    columns:
      - name: user_id
        tests: [not_null]
      - name: session_id
        tests: [not_null]

  - name: f_user_daily_activity
    tests:
      - unique:
          column_name: user_activity_fact_key
    columns:
      - name: user_activity_fact_key
        tests: [not_null]
      - name: user_id
        tests: [not_null]
      - name: activity_date
        tests: [not_null]

  - name: f_song_daily_performance
    tests:
      - unique:
          column_name: song_daily_fact_key
    columns:
      - name: song_daily_fact_key
        tests: [not_null]
      - name: activity_date
        tests: [not_null]
      - name: song
        tests: [not_null]
      - name: artist
        tests: [not_null]
