INSERT {{ BIGQUERY_DATASET }}.{{ PAGE_VIEW_EVENTS_TABLE }}
SELECT
    ts,
    sessionId,
    COALESCE(page, 'NA') AS page,
    COALESCE(auth, 'NA') AS auth,
    COALESCE(method, 'NA') AS method,
    COALESCE(status, 0) AS status,
    COALESCE(level, 'NA') AS level,
    itemInSession,
    COALESCE(city, 'NA') AS city,
    COALESCE(zip, 0) AS zip,
    COALESCE(state, 'NA') AS state,
    COALESCE(userAgent, 'NA') AS userAgent,
    COALESCE(lon, 0.0) AS lon,
    COALESCE(lat, 0.0) AS lat,
    COALESCE(userId, 0) AS userId,
    COALESCE(lastName, 'NA') AS lastName,
    COALESCE(firstName, 'NA') AS firstName,
    COALESCE(gender, 'NA') AS gender,
    COALESCE(registration, 0) AS registration,
    COALESCE(artist, 'NA') AS artist,
    COALESCE(song, 'NA') AS song,
    COALESCE(duration, -1.0) AS duration
FROM {{ BIGQUERY_DATASET }}.{{ PAGE_VIEW_EVENTS_TABLE}}_{{ logical_date.strftime("%m%d%H") }}